# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created: Sat Mar 04 17:54:17 2017
#      by: PyQt5 UI code generator 5.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(955, 912)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resource/weather-thunder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.year_label = QtWidgets.QLabel(self.centralwidget)
        self.year_label.setObjectName("year_label")
        self.horizontalLayout_1.addWidget(self.year_label)
        self.year_DateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.year_DateEdit.setObjectName("year_DateEdit")
        self.horizontalLayout_1.addWidget(self.year_DateEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_1.addItem(spacerItem)
        self.province_label = QtWidgets.QLabel(self.centralwidget)
        self.province_label.setObjectName("province_label")
        self.horizontalLayout_1.addWidget(self.province_label)
        self.province_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.province_comboBox.setObjectName("province_comboBox")
        self.province_comboBox.addItem("")
        self.province_comboBox.addItem("")
        self.horizontalLayout_1.addWidget(self.province_comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_1.addItem(spacerItem1)
        self.target_area_label = QtWidgets.QLabel(self.centralwidget)
        self.target_area_label.setObjectName("target_area_label")
        self.horizontalLayout_1.addWidget(self.target_area_label)
        self.target_area_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.target_area_comboBox.setObjectName("target_area_comboBox")
        self.horizontalLayout_1.addWidget(self.target_area_comboBox)
        spacerItem2 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_1.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_1.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_1, 0, 0, 1, 1)
        self.verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_1.addWidget(self.label)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.density_tab = QtWidgets.QWidget()
        self.density_tab.setObjectName("density_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.density_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.density_cell_label = QtWidgets.QLabel(self.density_tab)
        self.density_cell_label.setObjectName("density_cell_label")
        self.horizontalLayout_2.addWidget(self.density_cell_label)
        self.density_cell_spinBox = QtWidgets.QSpinBox(self.density_tab)
        self.density_cell_spinBox.setMaximum(30)
        self.density_cell_spinBox.setProperty("value", 10)
        self.density_cell_spinBox.setObjectName("density_cell_spinBox")
        self.horizontalLayout_2.addWidget(self.density_cell_spinBox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.density_class_label = QtWidgets.QLabel(self.density_tab)
        self.density_class_label.setObjectName("density_class_label")
        self.horizontalLayout_2.addWidget(self.density_class_label)
        self.density_class_spinBox = QtWidgets.QSpinBox(self.density_tab)
        self.density_class_spinBox.setMaximum(15)
        self.density_class_spinBox.setProperty("value", 10)
        self.density_class_spinBox.setObjectName("density_class_spinBox")
        self.horizontalLayout_2.addWidget(self.density_class_spinBox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.density_view = QtWidgets.QGraphicsView(self.density_tab)
        self.density_view.setObjectName("density_view")
        self.verticalLayout_2.addWidget(self.density_view)
        self.tabWidget.addTab(self.density_tab, "")
        self.day_tab = QtWidgets.QWidget()
        self.day_tab.setObjectName("day_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.day_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.day_cell_label = QtWidgets.QLabel(self.day_tab)
        self.day_cell_label.setObjectName("day_cell_label")
        self.horizontalLayout_3.addWidget(self.day_cell_label)
        self.day_cell_spinBox = QtWidgets.QSpinBox(self.day_tab)
        self.day_cell_spinBox.setMinimum(5)
        self.day_cell_spinBox.setMaximum(30)
        self.day_cell_spinBox.setProperty("value", 15)
        self.day_cell_spinBox.setObjectName("day_cell_spinBox")
        self.horizontalLayout_3.addWidget(self.day_cell_spinBox)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.day_class_label = QtWidgets.QLabel(self.day_tab)
        self.day_class_label.setObjectName("day_class_label")
        self.horizontalLayout_3.addWidget(self.day_class_label)
        self.day_class_spinBox = QtWidgets.QSpinBox(self.day_tab)
        self.day_class_spinBox.setMinimum(5)
        self.day_class_spinBox.setMaximum(15)
        self.day_class_spinBox.setProperty("value", 10)
        self.day_class_spinBox.setObjectName("day_class_spinBox")
        self.horizontalLayout_3.addWidget(self.day_class_spinBox)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.day_view = QtWidgets.QGraphicsView(self.day_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.day_view.sizePolicy().hasHeightForWidth())
        self.day_view.setSizePolicy(sizePolicy)
        self.day_view.setObjectName("day_view")
        self.verticalLayout_3.addWidget(self.day_view)
        self.tabWidget.addTab(self.day_tab, "")
        self.regions_stats_tab = QtWidgets.QWidget()
        self.regions_stats_tab.setObjectName("regions_stats_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.regions_stats_tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.province_stats_table = QtWidgets.QTableView(self.regions_stats_tab)
        self.province_stats_table.setObjectName("province_stats_table")
        self.verticalLayout_4.addWidget(self.province_stats_table)
        self.region_stats_table = QtWidgets.QTableView(self.regions_stats_tab)
        self.region_stats_table.setObjectName("region_stats_table")
        self.verticalLayout_4.addWidget(self.region_stats_table)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.regions_stats_tab, "")
        self.month_stats_tab = QtWidgets.QWidget()
        self.month_stats_tab.setObjectName("month_stats_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.month_stats_tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.month_stats_table = QtWidgets.QTableView(self.month_stats_tab)
        self.month_stats_table.setObjectName("month_stats_table")
        self.verticalLayout_6.addWidget(self.month_stats_table)
        self.month_stats_view = QtWidgets.QGraphicsView(self.month_stats_tab)
        self.month_stats_view.setObjectName("month_stats_view")
        self.verticalLayout_6.addWidget(self.month_stats_view)
        self.tabWidget.addTab(self.month_stats_tab, "")
        self.hour_stats_tab = QtWidgets.QWidget()
        self.hour_stats_tab.setObjectName("hour_stats_tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.hour_stats_tab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.hours_stats_table = QtWidgets.QTableView(self.hour_stats_tab)
        self.hours_stats_table.setObjectName("hours_stats_table")
        self.verticalLayout_9.addWidget(self.hours_stats_table)
        self.hour_stats_view = QtWidgets.QGraphicsView(self.hour_stats_tab)
        self.hour_stats_view.setObjectName("hour_stats_view")
        self.verticalLayout_9.addWidget(self.hour_stats_view)
        self.tabWidget.addTab(self.hour_stats_tab, "")
        self.intensity_stats_tab = QtWidgets.QWidget()
        self.intensity_stats_tab.setObjectName("intensity_stats_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.intensity_stats_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.intensity_stats_table = QtWidgets.QTableView(self.intensity_stats_tab)
        self.intensity_stats_table.setObjectName("intensity_stats_table")
        self.horizontalLayout_4.addWidget(self.intensity_stats_table)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.negative_view = QtWidgets.QGraphicsView(self.intensity_stats_tab)
        self.negative_view.setObjectName("negative_view")
        self.verticalLayout_7.addWidget(self.negative_view)
        self.positive_view = QtWidgets.QGraphicsView(self.intensity_stats_tab)
        self.positive_view.setObjectName("positive_view")
        self.verticalLayout_7.addWidget(self.positive_view)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.intensity_stats_tab, "")
        self.verticalLayout_1.addWidget(self.tabWidget)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_1.addWidget(self.progressBar)
        self.gridLayout.addLayout(self.verticalLayout_1, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 955, 23))
        self.menubar.setObjectName("menubar")
        self.file_menu = QtWidgets.QMenu(self.menubar)
        self.file_menu.setObjectName("file_menu")
        self.help_menu = QtWidgets.QMenu(self.menubar)
        self.help_menu.setObjectName("help_menu")
        self.action_menu = QtWidgets.QMenu(self.menubar)
        self.action_menu.setObjectName("action_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.help_action = QtWidgets.QAction(MainWindow)
        self.help_action.setObjectName("help_action")
        self.about_action = QtWidgets.QAction(MainWindow)
        self.about_action.setObjectName("about_action")
        self.export_charts_action = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resource/export_charts.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.export_charts_action.setIcon(icon1)
        self.export_charts_action.setObjectName("export_charts_action")
        self.export_doc_action = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resource/export_doc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.export_doc_action.setIcon(icon2)
        self.export_doc_action.setObjectName("export_doc_action")
        self.load_data_action = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resource/load_data.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.load_data_action.setIcon(icon3)
        self.load_data_action.setObjectName("load_data_action")
        self.execute_action = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resource/excute.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.execute_action.setIcon(icon4)
        self.execute_action.setObjectName("execute_action")
        self.open_doc_action = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("resource/open_doc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_doc_action.setIcon(icon5)
        self.open_doc_action.setObjectName("open_doc_action")
        self.open_charts_action = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("resource/open_charts.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_charts_action.setIcon(icon6)
        self.open_charts_action.setObjectName("open_charts_action")
        self.exit_action = QtWidgets.QAction(MainWindow)
        self.exit_action.setObjectName("exit_action")
        self.file_menu.addAction(self.open_doc_action)
        self.file_menu.addAction(self.open_charts_action)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.export_doc_action)
        self.file_menu.addAction(self.export_charts_action)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.exit_action)
        self.help_menu.addAction(self.help_action)
        self.help_menu.addAction(self.about_action)
        self.action_menu.addAction(self.load_data_action)
        self.action_menu.addAction(self.execute_action)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.action_menu.menuAction())
        self.menubar.addAction(self.help_menu.menuAction())
        self.toolBar.addAction(self.load_data_action)
        self.toolBar.addAction(self.execute_action)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.open_doc_action)
        self.toolBar.addAction(self.open_charts_action)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.export_doc_action)
        self.toolBar.addAction(self.export_charts_action)
        self.year_label.setBuddy(self.year_DateEdit)
        self.province_label.setBuddy(self.province_comboBox)
        self.target_area_label.setBuddy(self.target_area_comboBox)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "雷电公报"))
        self.year_label.setText(_translate("MainWindow", "年份"))
        self.year_DateEdit.setDisplayFormat(_translate("MainWindow", "yyyy"))
        self.province_label.setText(_translate("MainWindow", "省份"))
        self.province_comboBox.setItemText(0, _translate("MainWindow", "河南"))
        self.province_comboBox.setItemText(1, _translate("MainWindow", "浙江"))
        self.target_area_label.setText(_translate("MainWindow", "目标区域"))
        self.density_cell_label.setText(_translate("MainWindow", "插值网格大小"))
        self.density_class_label.setText(_translate("MainWindow", "制图分类数目"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.density_tab), _translate("MainWindow", "闪电密度分布图"))
        self.day_cell_label.setText(_translate("MainWindow", "插值半径大小"))
        self.day_class_label.setText(_translate("MainWindow", "制图分类数目"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.day_tab), _translate("MainWindow", "雷暴日分布图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.regions_stats_tab), _translate("MainWindow", "分区统计"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.month_stats_tab), _translate("MainWindow", "分月统计"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.hour_stats_tab), _translate("MainWindow", "分时段统计"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.intensity_stats_tab), _translate("MainWindow", "强度统计"))
        self.file_menu.setTitle(_translate("MainWindow", "文件"))
        self.help_menu.setTitle(_translate("MainWindow", "帮助"))
        self.action_menu.setTitle(_translate("MainWindow", "操作"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.help_action.setText(_translate("MainWindow", "使用说明"))
        self.help_action.setShortcut(_translate("MainWindow", "F1"))
        self.about_action.setText(_translate("MainWindow", "关于"))
        self.about_action.setShortcut(_translate("MainWindow", "F2"))
        self.export_charts_action.setText(_translate("MainWindow", "导出图表"))
        self.export_charts_action.setShortcut(_translate("MainWindow", "Alt+C"))
        self.export_doc_action.setText(_translate("MainWindow", "导出文档"))
        self.export_doc_action.setShortcut(_translate("MainWindow", "Alt+D"))
        self.load_data_action.setText(_translate("MainWindow", "加载数据"))
        self.load_data_action.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.execute_action.setText(_translate("MainWindow", "执行"))
        self.execute_action.setShortcut(_translate("MainWindow", "F5"))
        self.open_doc_action.setText(_translate("MainWindow", "打开文档"))
        self.open_doc_action.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.open_charts_action.setText(_translate("MainWindow", "打开图表"))
        self.open_charts_action.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.exit_action.setText(_translate("MainWindow", "退出"))
        self.exit_action.setShortcut(_translate("MainWindow", "F4"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

